### ISSUE TITLE
How to start docker prod container?

### ISSUE THREAD

**Issue by luebbert42** [pivotal/postfacto#324]
I want to evaluate postfacto and run the prod docker container to do so. 
I can't start the Docker container:

```

docker run postfacto/postfacto
rake aborted!
ActiveRecord::AdapterNotSpecified: The `production` database is not configured for the `production` environment.
```

What am I doing wrong? 
Is the db meant to run outside of the container and be configured via environment parameters somehow?

**Comment by textbook** [comment]
> Is the db meant to run outside of the container and be configured via environment parameters somehow?

Yes, exactly that; the `DATABASE_URL` env var tells the app where to find the DB (similarly `REDIS_URL` for the message queue, or if you're using Postgres you can set `USE_POSTGRES_FOR_ACTION_CABLE=true` and not have a separate message queue).

If you're using Docker you could do this with [Compose](https://docs.docker.com/compose/) via a `docker-compose.yml`, something like (untested):

```yml
version: "3.8"
services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD: example
  postfacto:
    image: postfacto/postfacto
    ports:
    - "3000:3000"
    environment:
    - DATABASE_URL=postgresql://postgres:example@postgres:5432/database
    - USE_POSTGRES_FOR_ACTION_CABLE=true
    links:
    - postgres
```
